---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by laure.
--- DateTime: 07/04/2025 19:12
---


VFW.LocalHeists = {}
local isPlayerAlrdyBraked = false

local heistLoaded = {}

local ped = {}
local bag, contextRegistered = nil, false
local function createHeistPoint(heistId)
    local heist = VFW.LocalHeists[heistId]
    if heist == nil then
        return
    end
    --if VFW.PlayerData.job and VFW.PlayerData.job.type ~= "faction" then
    --    return
    --end

    if heistLoaded[heistId] then
        return
    end

    heistLoaded[heistId] = true

    if not ped[heistId] then
        VFW.Streaming.RequestModel(heist.ped_model)
        ped[heistId] = CreatePed(4, heist.ped_model, heist.ped_position.x, heist.ped_position.y, heist.ped_position.z - 0.98, heist.ped_position.w, false, false)
    end

    SetModelAsNoLongerNeeded(model)
    SetEntityInvincible(ped[heistId], true)
    FreezeEntityPosition(ped[heistId], true)
    TaskStartScenarioInPlace(ped[heistId], "WORLD_HUMAN_CLIPBOARD", 0, true)
    SetEntityAsMissionEntity(ped[heistId], true, true)
    SetBlockingOfNonTemporaryEvents(ped[heistId], true)
    VFW.CreateBlipAndPoint("braquage" .. heist.id, vector3(heist.ped_position.x, heist.ped_position.y, heist.ped_position.z), "heist" .. heist.id, nil, 2, 0.8, nil, "Braquer", "E", "Braquage", {
        onPress = function()
            if GetCurrentPedWeapon(VFW.PlayerData.ped) ~= 1 or IsPedInMeleeCombat(PlayerPedId()) then
                VFW.ShowNotification({ type = "error", content = "Vous devez être armé pour braquer ce lieu." })
                return
            end

            local nbPolice = TriggerServerCallback("vfw:heist:getNbOfDuty", heist.id)
            local canStart = TriggerServerCallback("vfw:heist:canStartHeist", heist.id)

            if nbPolice < heist.cops_required then
                VFW.ShowNotification({ type = "ROUGE", content = "Il n'y a pas assez de policiers en service." })
                return
            end

            if not canStart then
                return
            end

            if isPlayerAlrdyBraked then
                VFW.ShowNotification({ type = "ROUGE", content = "Braquage en cour" })
                return
            end

            TriggerServerEvent('vfw:heists:startHeistAnimation', heist.id)

            TriggerServerEvent('core:alert:makeCall', "lspd", vector3(heist.ped_position.x, heist.ped_position.y, heist.ped_position.z), true, heist.heist_label, false, "illegal")
            TriggerServerEvent('core:alert:makeCall', "lssd", vector3(heist.ped_position.x, heist.ped_position.y, heist.ped_position.z), true, heist.heist_label, false, "illegal")

            local minReward = 200
            local givedReward = math.random(minReward, math.max(minReward + 1, heist.max_reward))
            local startTime = GetGameTimer()
            local totalDuration = 60000 -- 1 minute
            isPlayerAlrdyBraked = true

            LoadAnimDict('missheist_agency2ahands_up')
            LoadAnimDict('mp_am_hold_up')

            Citizen.CreateThread(function()
                while GetGameTimer() - startTime < totalDuration do
                    Wait(300)

                    if IsPedDeadOrDying(ped[heistId]) then
                        TriggerServerEvent('vfw:heists:endHeistAnimation', heistId, "~r~Apu est mort!!", true)
                        break
                    end

                    if #(GetEntityCoords(VFW.PlayerData.ped) - vector3(heist.ped_position.x, heist.ped_position.y, heist.ped_position.z)) >= 8 then
                        TriggerServerEvent('vfw:heists:endHeistAnimation', heistId, "~r~Vous avez quitté la zone!", true)
                        break
                    end

                    if bag and DoesEntityExist(bag) and #(GetEntityCoords(VFW.PlayerData.ped) - GetEntityCoords(bag)) <= 3.0 and not contextRegistered then
                        DeleteEntity(bag)
                        TriggerServerEvent("vfw:heists:giveReward", givedReward, heist.id)
                        TriggerServerEvent('vfw:heists:endHeistAnimation', heistId, "~g~Braquage réussi!", false)
                        contextRegistered = true
                    end
                end

                if not isPlayerAlrdyBraked then
                    TriggerServerEvent('vfw:heists:endHeistAnimation', heistId, "~g~Braquage terminé!", false)
                end
            end)
        end
    }, { "#E85D5D", "#E63B3B" })

    function LoadAnimDict(dict)
        while not HasAnimDictLoaded(dict) do
            RequestAnimDict(dict)
            Wait(50)
        end
    end

    function EndHeist(heistId, message, failed)
        ClearPedTasks(ped[heistId])
        Citizen.SetTimeout(1000, function()
            ClearPedTasksImmediately(ped[heistId])
            --FreezeEntityPosition(ped, true)
        end)
        SetEntityInvincible(ped[heistId], true)

        if bag and DoesEntityExist(bag) then
            DeleteEntity(bag)
        end

        VFW.ShowNotification({ type = failed and "ROUGE" or "VERT", content = message })
        TriggerServerEvent('vfw:heists:setBrackedStatus', heist.id, false)
        isPlayerAlrdyBraked = false
    end
end

RegisterNetEvent('vfw:heists:syncStartHeistAnimation')
AddEventHandler('vfw:heists:syncStartHeistAnimation', function(heistId)
    if not ped[heistId] or not DoesEntityExist(ped[heistId]) then
        return
    end

    LoadAnimDict('missheist_agency2ahands_up')
    LoadAnimDict('mp_am_hold_up')

    TaskPlayAnim(ped[heistId], "missheist_agency2ahands_up", "handsup_anxious", 8.0, -8.0, -1, 1, 0, false, false, false)

    Citizen.SetTimeout(5000, function()
        if not DoesEntityExist(ped[heistId]) or IsPedDeadOrDying(ped[heistId]) then
            return
        end
        TaskPlayAnim(ped[heistId], "mp_am_hold_up", "holdup_victim_20s", 8.0, -8.0, -1, 2, 0, false, false, false)
    end)

    Citizen.SetTimeout(11000, function()
        if not DoesEntityExist(ped[heistId]) then
            return
        end
        local cashRegister = GetClosestObjectOfType(GetEntityCoords(ped[heistId]), 5.0, GetHashKey('prop_till_01'))
        if DoesEntityExist(cashRegister) then
            CreateModelSwap(GetEntityCoords(cashRegister), 0.5, GetHashKey('prop_till_01'), GetHashKey('prop_till_01_dam'), false)
        end
    end)

    Citizen.SetTimeout(20000, function()
        if not DoesEntityExist(ped[heistId]) then
            return
        end
        local model = GetHashKey('prop_poly_bag_01')
        VFW.Streaming.RequestModel(model)
        bag = CreateObject(model, GetEntityCoords(ped[heistId]), true, true, false)
        AttachEntityToEntity(bag, ped[heistId], GetPedBoneIndex(ped[heistId], 60309), 0.1, -0.11, 0.08, 0.0, -75.0, -75.0, 1, 1, 0, 0, 2, 1)

        if DoesEntityExist(bag) and not IsPedDeadOrDying(ped[heistId]) then
            DetachEntity(bag, true, false)
            ApplyForceToEntity(bag, 3, vector3(0.0, 50.0, 0.0), 0.0, 0.0, 0.0, 0, true, true, false, false, true)
        end
    end)
end)

RegisterNetEvent("stopheistanimation")
AddEventHandler("stopheistanimation", function(heistId)
    if ped[heistId] and DoesEntityExist(ped[heistId]) then
        ClearPedTasks(ped[heistId])
        Citizen.SetTimeout(1000, function()
            ClearPedTasksImmediately(ped[heistId])
            --FreezeEntityPosition(ped, true)
        end)
        SetEntityInvincible(ped[heistId], true)

        if bag and DoesEntityExist(bag) then
            DeleteEntity(bag)
        end
    end
end)

RegisterNetEvent('vfw:heists:syncEndHeistAnimation')
AddEventHandler('vfw:heists:syncEndHeistAnimation', function(heistId, message, failed)
    if ped[heistId] and DoesEntityExist(ped[heistId]) then
        EndHeist(heistId, message, failed)
    end
end)

RegisterNetEvent("vfw:setFaction", function(faction)
    if faction.name ~= "nocrew" then
        for k, v in pairs(VFW.LocalHeists) do
            createHeistPoint(k)
        end
    end
end)

RegisterNetEvent("vfw:playerReady", function()
    local heists = TriggerServerCallback("vfw:heists:all")
    VFW.LocalHeists = heists

    while not VFW.PlayerData do
        Wait(100)
    end

    while not VFW.PlayerData.faction do
        Wait(100)
    end

    if VFW.PlayerData.faction.name == "nocrew" then
        return
    end

    for k, v in pairs(VFW.LocalHeists) do
        createHeistPoint(k)
    end
end)

RegisterNetEvent("vfw:heist:addNewHeist", function(heist)
    VFW.LocalHeists[heist.id] = heist

    if VFW.PlayerData.faction.name == "nocrew" then
        return
    end

    createHeistPoint(heist.id)

end)
--function VFW.CreateBlipAndPoint(name, positions, key, blipSprite, blipColor, blipScale, blipLabel, interactLabel, interactKey, interactIcons, action, colors)

