---
--- Generated by CfxEmmyLua(https://gitlab.madelew.com/wmade/cfx-EmmyLua/)
--- Created by laure.
--- DateTime: 25/04/2025 18:02
--- Version: 1.0.0
---


local craftLoaded = nil

local function GetInventoryRecipe(Items)
    local filteredInventory = {}
    local addedItems = {}
    for _, mI in pairs(VFW.PlayerData.inventory) do
        for _, recipe in pairs(Items) do
            for _, item in pairs(recipe.recipe) do
                if mI.name == item.name and not addedItems[mI.name] then
                    table.insert(filteredInventory, { name = mI.name, label = VFW.Items[mI.name].label, amount = mI.count })
                    addedItems[mI.name] = true
                end
            end
        end
    end
    return filteredInventory
end

local loadCraftPos = function()

    if craftLoaded then
        Worlds.Zone.Remove(craftLoaded)
        craftLoaded = nil
    end

    local pos = TriggerServerCallback("core:faction:requestCraftPosition")
    if pos == nil then
        return
    end

    craftLoaded =  Worlds.Zone.Create(pos, 1.5, false, function()
        VFW.RegisterInteraction(("Craft:%s"):format(VFW.PlayerData.faction.type), function()
            local craftsItems = TriggerServerCallback("core:faction:getMyCraftItems")
            local filteredInventory = GetInventoryRecipe(craftsItems)
            VFW.SetLastRecipe(craftsItems)
            VFW.Nui.Craft(true, craftsItems, filteredInventory, "Armes")

        end)
    end, function()
        VFW.RemoveInteraction(("Craft:%s"):format(VFW.PlayerData.faction.type))
    end, "Craft", "E", "Braquage")
end

RegisterNetEvent("vfw:setFaction", function()
    loadCraftPos()
end)

RegisterNetEvent("crew:client:setType", function(type)
    VFW.PlayerData.faction.type = type
    loadCraftPos()
end)

RegisterNetEvent("vfw:playerLoaded", function()
    while not VFW.PlayerData do
        Wait(1000)
    end
    while not VFW.PlayerData.faction do
        Wait(1000)
    end
    local crew = VFW.PlayerData.faction
    if not crew.type then
        return
    end

    loadCraftPos()

end)



