---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by laure.
--- DateTime: 07/04/2025 18:00
---


VFW.Heists = {}

RegisterServerCallback("vfw:heists:all", function(src, ...)
    return VFW.Heists
end)

RegisterNetEvent("vfw:heists:add", function(data)
    local src = source
    local xPlayer = VFW.GetPlayerFromId(src)
    local playerGlobal = VFW.GetPlayerGlobalFromId(src)
    if not playerGlobal.permissions["staff_menu"] then
        return xPlayer.showNotification({
            type = "error",
            content = "Vous n'avez pas la permission d'ajouter un heist.",
        })
    end

    MySQL.Async.execute("INSERT INTO heists (heist_type, heist_label, ped_model, ped_position, cops_required, crew_level_required, max_reward, heist_location, xp_reward) VALUES (@heist_type, @heist_label, @ped_model, @ped_position, @cops_required, @crew_level_required, @max_reward, @heist_location, @xp_reward)", {
        ["@heist_type"] = data.heist_type,
        ["@heist_label"] = data.heist_label,
        ["@ped_model"] = data.ped_model,
        ["@ped_position"] = json.encode(data.ped_position),
        ["@cops_required"] = data.cops_required,
        ["@crew_level_required"] = data.crew_level_required,
        ["@max_reward"] = data.max_reward,
        ["@heist_location"] = data.heist_location,
        ["@xp_reward"] = data.xp_reward,
    }, function(rowsAffected)

        print("Heist ajouté : ", json.encode(data))
        if rowsAffected then
            xPlayer.showNotification({
                type = "success",
                content = "Heist ajouté avec succès.",
            })
            VFW.Heists[rowsAffected] = CreateHeists(
                    rowsAffected,
                    data.heist_type,
                    "Braquage " .. data.heist_label,
                    data.ped_model,
                    data.ped_position,
                    data.cops_required,
                    data.crew_level_required,
                    data.max_reward,
                    data.heist_location,
                    data.xp_reward
            )

            TriggerClientEvent("vfw:heist:addNewHeist", -1, VFW.Heists[rowsAffected])
        else
            xPlayer.showNotification({
                type = "error",
                content = "Erreur lors de l'ajout de l'heist.",
            })
        end
    end)


end)

MySQL.ready(function()
    MySQL.Async.fetchAll("SELECT * FROM heists", function(result)
        if not result[1] then
            return
        end
        for i = 1, #result do
            local currentHeist = result[i]
            VFW.Heists[currentHeist.id] = CreateHeists(
                    currentHeist.id,
                    currentHeist.heist_type,
                    "Braquage " .. currentHeist.heist_label,
                    currentHeist.ped_model,
                    json.decode(currentHeist.ped_position),
                    currentHeist.cops_required,
                    currentHeist.crew_level_required,
                    currentHeist.max_reward,
                    currentHeist.heist_location,
                    currentHeist.xp_reward
            )
        end
    end)
end)

RegisterNetEvent('syncEntity')
AddEventHandler('syncEntity', function(netId, model)
    if netId and model then
        -- Broadcast to all clients except sender
        TriggerClientEvent('receiveEntity', -1, netId, model, source)
    end
end)
