---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by laure.
--- DateTime: 07/04/2025 20:22
---

VFW.PlayersHeists = {}
VFW.HeistsBracked = {}


--local updateXpHeist = {
--    ["barber"] = 30,
--    ["binco"] = 50,
--    ["sup"] = 20,
--    ["tattoo"] = 50,
--    ["ammu"] = 100
--}

RegisterServerCallback("vfw:heist:getNbOfDuty", function(src, heistId)
    local xPlayer = VFW.GetPlayerFromId(src)

    if xPlayer == nil then
        return 0
    end

    if xPlayer.getFaction().name == "nocrew" then
        return 0
    end

    local players = VFW.GetPlayers()

    local currentHeist = VFW.Heists[heistId]
    if currentHeist == nil then
        return 0
    end

    local cops = 0
    for i = 1, #players do
        local v = players[i]
        local player = VFW.GetPlayerFromId(v)

        if player then
            if player.job.name == "lspd" or player.job.name == "lssd" and player.job.onDuty then
                cops = cops + 1
            end
        end
    end

    return cops
end)

RegisterNetEvent("vfw:heists:giveReward", function(givedReward, heistId)
    local src = source
    local xPlayer = VFW.GetPlayerFromId(src)

    if xPlayer == nil then
        return false
    end

    if xPlayer.getFaction().name == "nocrew" then
        return false
    end

    local playerCrew = VFW.GetCrewByName(xPlayer.getFaction().name)
    if playerCrew == nil then
        return false
    end

    local xp_reward = VFW.Heists[heistId].xp_reward

    playerCrew.addXp(xp_reward or 10)

    if VFW.PlayersHeists[xPlayer.identifier] == nil then
        VFW.PlayersHeists[xPlayer.identifier] = 0
    end
    VFW.PlayersHeists[xPlayer.identifier] = VFW.PlayersHeists[xPlayer.identifier] + 1

    VFW.HeistsBracked[heistId] = os.time()

    xPlayer.addMoney(givedReward)
    playerCrew.addActivity(xPlayer.identifier, "heist")


    return true
end)


local LEVELS <const> = {
    { rank = "D", level = 5, xpRequired = 0 },
    { rank = "C", level = 10, xpRequired = 1000  },
    { rank = "B", level = 25, xpRequired = 3000   },
    { rank = "A", level = 50, xpRequired = 7000  },
    { rank = "S", level = 100, xpRequired = 14000  }
}


RegisterServerCallback("vfw:heist:canStartHeist", function(src, heistId)
    local xPlayer = VFW.GetPlayerFromId(src)

    if xPlayer == nil then
        return false
    end

    if xPlayer.getFaction().name == "nocrew" then
        return false
    end

    if VFW.HeistsBracked[heistId] ~= nil then
        xPlayer.showNotification({
            type = "ROUGE",
            content = "Les caisses sont vide.",
        })
        return false
    end

    local crew = VFW.GetCrewByName(xPlayer.getFaction().name)
    if crew == nil then
        return false
    end

    local xpRequiredForStart = nil

    for i = 1, #LEVELS do
        if LEVELS[i].rank == VFW.Heists[heistId].crew_level_required then
            xpRequiredForStart = LEVELS[i].xpRequired
            break
        end
    end



    if crew.getXP() < xpRequiredForStart then
        xPlayer.showNotification({
            type = "ROUGE",
            content = "Vous n'avez pas le niveau requis.",
        })
        return false
    end

    if VFW.PlayersHeists[xPlayer.identifier] == nil then
        VFW.PlayersHeists[xPlayer.identifier] = 0
    end

    if VFW.PlayersHeists[xPlayer.identifier] < 3 then
        return true
    end

    return false
end)

CreateThread(function()
    while true do
        for k, v in pairs(VFW.HeistsBracked) do
            if os.time() - v >= 3600 then
                VFW.HeistsBracked[k] = nil
            end
        end

        Wait(1000 * 60 * 60)
    end
end)

RegisterNetEvent('vfw:heists:startHeistAnimation')
AddEventHandler('vfw:heists:startHeistAnimation', function(heistId)
    TriggerEvent('vfw:heists:setBrackedStatus', heistId, true)

    TriggerClientEvent('vfw:heists:syncStartHeistAnimation', -1, heistId)
end)

-- Événement déclenché lorsqu'un braquage se termine
RegisterNetEvent('vfw:heists:endHeistAnimation')
AddEventHandler('vfw:heists:endHeistAnimation', function(heistId, message, failed)
    TriggerClientEvent('vfw:heists:syncEndHeistAnimation', source, heistId, message, failed)
    TriggerClientEvent("stopheistanimation", -1, heistId)

    TriggerEvent('vfw:heists:setBrackedStatus', heistId, false)
end)


--local updateLevelHeist = {
--    ["barber"] = "C",
--    ["binco"] = "B",
--    ["sup"] = "B",
--    ["tattoo"] = "B",
--    ["ammu"] = "A"
--}
--

--
--RegisterCommand("fixheist", function()
--    MySQL.Async.fetchAll("SELECT * FROM heists", {}, function(result)
--        for i = 1, #result do
--            local heist = result[i]
--            local level = updateLevelHeist[heist.heist_type]
--            local xp = updateXpHeist[heist.heist_type]
--
--            MySQL.Async.execute("UPDATE heists SET crew_level_required = @level, xp_reward = @xp WHERE id = @id", {
--                ['@level'] = level,
--                ['@xp'] = xp,
--                ['@id'] = heist.id
--            }, function(rowsChanged)
--                print("Updated heist " .. heist.heist_label .. " with level " .. level .. " and xp " .. xp)
--            end)
--
--        end
--    end)
--end)