Config.DefaultWeaponTints = {
    [0] = "skin par défaut",
    [1] = "skin vert",
    [2] = "skin doré",
    [3] = "skin rose",
    [4] = "skin militaire",
    [5] = "skin bleu",
    [6] = "skin orange",
    [7] = "skin platine",
}
Config.MK2WeaponTints = {
    [0]  = "noir classique",
    [1]  = "gris classique",
    [2]  = "deux tons classiques",
    [3]  = "blanc classique",
    [4]  = "beige classique",
    [5]  = "vert classique",
    [6]  = "bleu classique",
    [7]  = "terre classique",
    [8]  = "marron noir classique",
    [9]  = "rouge contrasté",
    [10] = "bleu contrasté",
    [11] = "jaune contrasté",
    [12] = "orange contrasté",
    [13] = ('tint_bold_pink'),
    [14] = ('tint_bold_purple_yellow'),
    [15] = ('tint_bold_orange'),
    [16] = ('tint_bold_green_purple'),
    [17] = ('tint_bold_red_feat'),
    [18] = ('tint_bold_green_feat'),
    [19] = ('tint_bold_cyan_feat'),
    [20] = ('tint_bold_yellow_feat'),
    [21] = ('tint_bold_red_white'),
    [22] = ('tint_bold_blue_white'),
    [23] = ('tint_metallic_gold'),
    [24] = ('tint_metallic_platinum'),
    [25] = ('tint_metallic_gray_lilac'),
    [26] = ('tint_metallic_purple_lime'),
    [27] = ('tint_metallic_red'),
    [28] = ('tint_metallic_green'),
    [29] = ('tint_metallic_blue'),
    [30] = ('tint_metallic_white_aqua'),
    [31] = ('tint_metallic_orange_yellow'),
    [32] = "rouge jaune métallique"
}

Config.Weapons = {
    -- Melee
    { name = "WEAPON_DAGGER", label = ("weapon_dagger"), components = {} },
    { name = "WEAPON_BAT", label = ("weapon_bat"), components = {} },
    { name = "WEAPON_BATTLEAXE", label = ("weapon_battleaxe"), components = {} },
    {
        name = "WEAPON_KNUCKLE",
        label = ("weapon_knuckle"),
        components = {
            { name = "knuckle_base", label = ("component_knuckle_base"), hash = 'COMPONENT_KNUCKLE_VARMOD_BASE' },
            { name = "knuckle_pimp", label = ("component_knuckle_pimp"), hash = 'COMPONENT_KNUCKLE_VARMOD_PIMP' },
            { name = "knuckle_ballas", label = ("component_knuckle_ballas"), hash = 'COMPONENT_KNUCKLE_VARMOD_BALLAS' },
            { name = "knuckle_dollar", label = ("component_knuckle_dollar"), hash = 'COMPONENT_KNUCKLE_VARMOD_DOLLAR' },
            { name = "knuckle_diamond", label = ("component_knuckle_diamond"), hash = 'COMPONENT_KNUCKLE_VARMOD_DIAMOND' },
            { name = "knuckle_hate", label = ("component_knuckle_hate"), hash = 'COMPONENT_KNUCKLE_VARMOD_HATE' },
            { name = "knuckle_love", label = ("component_knuckle_love"), hash = 'COMPONENT_KNUCKLE_VARMOD_LOVE' },
            { name = "knuckle_player", label = ("component_knuckle_player"), hash = 'COMPONENT_KNUCKLE_VARMOD_PLAYER' },
            { name = "knuckle_king", label = ("component_knuckle_king"), hash = 'COMPONENT_KNUCKLE_VARMOD_KING' },
            { name = "knuckle_vagos", label = ("component_knuckle_vagos"), hash = 'COMPONENT_KNUCKLE_VARMOD_VAGOS' },
        },
    },
    { name = "WEAPON_BOTTLE", label = ("weapon_bottle"), components = {} },
    { name = "WEAPON_CROWBAR", label = ("weapon_crowbar"), components = {} },
    { name = "WEAPON_FLASHLIGHT", label = ("weapon_flashlight"), components = {} },
    { name = "WEAPON_GOLFCLUB", label = ("weapon_golfclub"), components = {} },
    { name = "WEAPON_HAMMER", label = ("weapon_hammer"), components = {} },
    { name = "WEAPON_HATCHET", label = ("weapon_hatchet"), components = {} },
    { name = "WEAPON_KNIFE", label = ("weapon_knife"), components = {} },
    { name = "WEAPON_MACHETE", label = ("weapon_machete"), components = {} },
    { name = "WEAPON_NIGHTSTICK", label = ("weapon_nightstick"), components = {} },
    { name = "WEAPON_WRENCH", label = ("weapon_wrench"), components = {} },
    { name = "WEAPON_POOLCUE", label = ("weapon_poolcue"), components = {} },
    { name = "WEAPON_STONE_HATCHET", label = ("weapon_stone_hatchet"), components = {} },
    {
        name = "WEAPON_SWITCHBLADE",
        label = ("weapon_switchblade"),
        components = {
            { name = "handle_default", label = ("component_handle_default"), hash = 'COMPONENT_SWITCHBLADE_VARMOD_BASE' },
            { name = "handle_vip", label = ("component_handle_vip"), hash = 'COMPONENT_SWITCHBLADE_VARMOD_VAR1' },
            { name = "handle_bodyguard", label = ("component_handle_bodyguard"), hash = 'COMPONENT_SWITCHBLADE_VARMOD_VAR2' },
        },
    },
    -- Handguns
    {
        name = "WEAPON_APPISTOL",
        label = ("weapon_appistol"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_APPISTOL_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_APPISTOL_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_SUPP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_APPISTOL_VARMOD_LUXE' },
        },
    },
    { name = "WEAPON_CERAMICPISTOL", label = ("weapon_ceramicpistol"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' } },
    {
        name = "WEAPON_COMBATPISTOL",
        label = ("weapon_combatpistol"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_COMBATPISTOL_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_COMBATPISTOL_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_SUPP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER' },
        },
    },
    { name = "WEAPON_DOUBLEACTION", label = ("weapon_doubleaction"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' } },
    { name = "WEAPON_NAVYREVOLVER", label = ("weapon_navyrevolver"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' } },
    { name = "WEAPON_FLAREGUN", label = ("weapon_flaregun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_flaregun"), hash = 'AMMO_FLAREGUN' } },
    { name = "WEAPON_GADGETPISTOL", label = ("weapon_gadgetpistol"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' } },
    {
        name = "WEAPON_HEAVYPISTOL",
        label = ("weapon_heavypistol"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_HEAVYPISTOL_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_HEAVYPISTOL_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_SUPP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_HEAVYPISTOL_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_REVOLVER",
        label = ("weapon_revolver"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_REVOLVER_CLIP_01' },
            { name = "vip_finish", label = ("component_vip_finish"), hash = 'COMPONENT_REVOLVER_VARMOD_BOSS' },
            { name = "bodyguard_finish", label = ("component_bodyguard_finish"), hash = 'COMPONENT_REVOLVER_VARMOD_GOON' },
        },
    },
    {
        name = "WEAPON_REVOLVER_MK2",
        label = ("weapon_revolver_mk2"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_REVOLVER_MK2_CLIP_01' },
            { name = "ammo_tracer", label = ("component_ammo_tracer"), hash = 'COMPONENT_REVOLVER_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = ("component_ammo_incendiary"), hash = 'COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY' },
            { name = "ammo_hollowpoint", label = ("component_ammo_hollowpoint"), hash = 'COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT' },
            { name = "ammo_fmj", label = ("component_ammo_fmj"), hash = 'COMPONENT_REVOLVER_MK2_CLIP_FMJ' },
            { name = "scope_holo", label = ("component_scope_holo"), hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_small", label = ("component_ammo_fmj"), hash = 'COMPONENT_AT_SCOPE_MACRO_MK2' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "compensator", label = ("component_compensator"), hash = 'COMPONENT_AT_PI_COMP_03' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_REVOLVER_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_REVOLVER_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_REVOLVER_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_REVOLVER_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_REVOLVER_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_REVOLVER_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_REVOLVER_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_REVOLVER_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_REVOLVER_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_REVOLVER_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_REVOLVER_MK2_CAMO_IND_01' },
        },
    },
    { name = "WEAPON_MARKSMANPISTOL", label = ("weapon_marksmanpistol"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' } },
    {
        name = "WEAPON_PISTOL",
        label = ("weapon_pistol"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_PISTOL_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_PISTOL_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_SUPP_02' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_PISTOL_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_PISTOL_MK2",
        label = ("weapon_pistol_mk2"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_PISTOL_MK2_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_PISTOL_MK2_CLIP_02' },
            { name = "ammo_tracer", label = ("component_ammo_tracer"), hash = 'COMPONENT_PISTOL_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = ("component_ammo_incendiary"), hash = 'COMPONENT_PISTOL_MK2_CLIP_INCENDIARY' },
            { name = "ammo_hollowpoint", label = ("component_ammo_hollowpoint"), hash = 'COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT' },
            { name = "ammo_fmj", label = ("component_ammo_fmj"), hash = 'COMPONENT_PISTOL_MK2_CLIP_FMJ' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_PI_RAIL' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_PI_FLSH_02' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_SUPP_02' },
            { name = "compensator", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_COMP' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_PISTOL_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_PISTOL_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_PISTOL_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_PISTOL_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_PISTOL_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_PISTOL_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_PISTOL_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_PISTOL_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_PISTOL_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_PISTOL_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_PISTOL_MK2_CAMO_IND_01' },
            { name = "camo_slide_finish", label = ("component_camo_slide_finish"), hash = 'COMPONENT_PISTOL_MK2_CAMO_SLIDE' },
            { name = "camo_slide_finish2", label = ("component_camo_slide_finish2"), hash = 'COMPONENT_PISTOL_MK2_CAMO_02_SLIDE' },
            { name = "camo_slide_finish3", label = ("component_camo_slide_finish3"), hash = 'COMPONENT_PISTOL_MK2_CAMO_03_SLIDE' },
            { name = "camo_slide_finish4", label = ("component_camo_slide_finish4"), hash = 'COMPONENT_PISTOL_MK2_CAMO_04_SLIDE' },
            { name = "camo_slide_finish5", label = ("component_camo_slide_finish5"), hash = 'COMPONENT_PISTOL_MK2_CAMO_05_SLIDE' },
            { name = "camo_slide_finish6", label = ("component_camo_slide_finish6"), hash = 'COMPONENT_PISTOL_MK2_CAMO_06_SLIDE' },
            { name = "camo_slide_finish7", label = ("component_camo_slide_finish7"), hash = 'COMPONENT_PISTOL_MK2_CAMO_07_SLIDE' },
            { name = "camo_slide_finish8", label = ("component_camo_slide_finish8"), hash = 'COMPONENT_PISTOL_MK2_CAMO_08_SLIDE' },
            { name = "camo_slide_finish9", label = ("component_camo_slide_finish9"), hash = 'COMPONENT_PISTOL_MK2_CAMO_09_SLIDE' },
            { name = "camo_slide_finish10", label = ("component_camo_slide_finish10"), hash = 'COMPONENT_PISTOL_MK2_CAMO_10_SLIDE' },
            { name = "camo_slide_finish11", label = ("component_camo_slide_finish11"), hash = 'COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE' },
        },
    },
    {
        name = "WEAPON_PISTOL50",
        label = ("weapon_pistol50"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_PISTOL50_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_PISTOL50_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_PISTOL50_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_SNSPISTOL",
        label = ("weapon_snspistol"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_SNSPISTOL_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_SNSPISTOL_CLIP_02' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_SNSPISTOL_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_SNSPISTOL_MK2",
        label = ("weapon_snspistol_mk2"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_02' },
            { name = "ammo_tracer", label = ("component_ammo_tracer"), hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = ("component_ammo_incendiary"), hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY' },
            { name = "ammo_hollowpoint", label = ("component_ammo_hollowpoint"), hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT' },
            { name = "ammo_fmj", label = ("component_ammo_fmj"), hash = 'COMPONENT_SNSPISTOL_MK2_CLIP_FMJ' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_PI_RAIL_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_PI_FLSH_03' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_SUPP_02' },
            { name = "compensator", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_COMP_02' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_IND_01' },
            { name = "camo_slide_finish", label = ("component_camo_slide_finish"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE' },
            { name = "camo_slide_finish2", label = ("component_camo_slide_finish2"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE' },
            { name = "camo_slide_finish3", label = ("component_camo_slide_finish3"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE' },
            { name = "camo_slide_finish4", label = ("component_camo_slide_finish4"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE' },
            { name = "camo_slide_finish5", label = ("component_camo_slide_finish5"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE' },
            { name = "camo_slide_finish6", label = ("component_camo_slide_finish6"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE' },
            { name = "camo_slide_finish7", label = ("component_camo_slide_finish7"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE' },
            { name = "camo_slide_finish8", label = ("component_camo_slide_finish8"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE' },
            { name = "camo_slide_finish9", label = ("component_camo_slide_finish9"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE' },
            { name = "camo_slide_finish10", label = ("component_camo_slide_finish10"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE' },
            { name = "camo_slide_finish11", label = ("component_camo_slide_finish11"), hash = 'COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE' },
        },
    },
    { name = "WEAPON_STUNGUN", label = ("weapon_stungun"), tints = Config.DefaultWeaponTints, components = {} },
    { name = "WEAPON_STUNROD", label = ("weapon_stunrod"), tints = Config.DefaultWeaponTints, components = {} },
    { name = "WEAPON_RAYPISTOL", label = ("weapon_raypistol"), tints = Config.DefaultWeaponTints, components = {} },
    {
        name = "WEAPON_VINTAGEPISTOL",
        label = ("weapon_vintagepistol"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_VINTAGEPISTOL_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_VINTAGEPISTOL_CLIP_02' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_SUPP' },
        },
    },
    -- Shotguns
    {
        name = "WEAPON_ASSAULTSHOTGUN",
        label = ("weapon_assaultshotgun"),
        ammo = { label = ("ammo_shells"), hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_ASSAULTSHOTGUN_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_ASSAULTSHOTGUN_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
        },
    },
    { name = "WEAPON_AUTOSHOTGUN", label = ("weapon_autoshotgun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_shells"), hash = 'AMMO_SHOTGUN' } },
    {
        name = "WEAPON_BULLPUPSHOTGUN",
        label = ("weapon_bullpupshotgun"),
        ammo = { label = ("ammo_shells"), hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
        },
    },
    {
        name = "WEAPON_COMBATSHOTGUN",
        label = ("weapon_combatshotgun"),
        ammo = { label = ("ammo_shells"), hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
        },
    },
    { name = "WEAPON_DBSHOTGUN", label = ("weapon_dbshotgun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_shells"), hash = 'AMMO_SHOTGUN' } },
    {
        name = "WEAPON_HEAVYSHOTGUN",
        label = ("weapon_heavyshotgun"),
        ammo = { label = ("ammo_shells"), hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_HEAVYSHOTGUN_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_HEAVYSHOTGUN_CLIP_02' },
            { name = "clip_drum", label = ("component_clip_drum"), hash = 'COMPONENT_HEAVYSHOTGUN_CLIP_03' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
        },
    },
    { name = "WEAPON_MUSKET", label = ("weapon_musket"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_rounds"), hash = 'AMMO_SHOTGUN' } },
    {
        name = "WEAPON_PUMPSHOTGUN",
        label = ("weapon_pumpshotgun"),
        ammo = { label = ("ammo_shells"), hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_SR_SUPP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_PUMPSHOTGUN_MK2",
        label = ("weapon_pumpshotgun_mk2"),
        ammo = { label = ("ammo_shells"), hash = 'AMMO_SHOTGUN' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "shells_default", label = ("component_shells_default"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_01' },
            { name = "shells_incendiary", label = ("component_shells_incendiary"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY' },
            { name = "shells_armor", label = ("component_shells_armor"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING' },
            { name = "shells_hollowpoint", label = ("component_shells_hollowpoint"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT' },
            { name = "shells_explosive", label = ("component_shells_explosive"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE' },
            { name = "scope_holo", label = ("component_scope_holo"), hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_small", label = ("component_scope_small"), hash = 'COMPONENT_AT_SCOPE_MACRO_MK2' },
            { name = "scope_medium", label = ("component_scope_medium"), hash = 'COMPONENT_AT_SCOPE_SMALL_MK2' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_SR_SUPP_03' },
            { name = "muzzle_squared", label = ("component_muzzle_squared"), hash = 'COMPONENT_AT_MUZZLE_08' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_SAWNOFFSHOTGUN",
        label = ("weapon_sawnoffshotgun"),
        ammo = { label = ("ammo_shells"), hash = 'AMMO_SHOTGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE' },
        },
    },
    -- SMG & LMG
    {
        name = "WEAPON_ASSAULTSMG",
        label = ("weapon_assaultsmg"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SMG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_ASSAULTSMG_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_ASSAULTSMG_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_MACRO' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_COMBATMG",
        label = ("weapon_combatmg"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_MG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_COMBATMG_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_COMBATMG_CLIP_02' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_MEDIUM' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_COMBATMG_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_COMBATMG_MK2",
        label = ("weapon_combatmg_mk2"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_MG' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_COMBATMG_MK2_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_COMBATMG_MK2_CLIP_02' },
            { name = "ammo_tracer", label = ("component_ammo_tracer"), hash = 'COMPONENT_COMBATMG_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = ("component_ammo_incendiary"), hash = 'COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY' },
            { name = "ammo_hollowpoint", label = ("component_ammo_hollowpoint"), hash = 'COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = ("component_ammo_fmj"), hash = 'COMPONENT_COMBATMG_MK2_CLIP_FMJ' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "scope_holo", label = ("component_scope_holo"), hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_medium", label = ("component_scope_medium"), hash = 'COMPONENT_AT_SCOPE_SMALL_MK2' },
            { name = "scope_large", label = ("component_scope_large"), hash = 'COMPONENT_AT_SCOPE_MEDIUM_MK2' },
            { name = "muzzle_flat", label = ("component_muzzle_flat"), hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = ("component_muzzle_tactical"), hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = ("component_muzzle_fat"), hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = ("component_muzzle_precision"), hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = ("component_muzzle_heavy"), hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = ("component_muzzle_slanted"), hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = ("component_muzzle_split"), hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "barrel_default", label = ("component_barrel_default"), hash = 'COMPONENT_AT_MG_BARREL_01' },
            { name = "barrel_heavy", label = ("component_barrel_heavy"), hash = 'COMPONENT_AT_MG_BARREL_02' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_COMBATMG_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_COMBATMG_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_COMBATMG_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_COMBATMG_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_COMBATMG_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_COMBATMG_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_COMBATMG_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_COMBATMG_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_COMBATMG_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_COMBATMG_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_COMBATMG_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_COMBATPDW",
        label = ("weapon_combatpdw"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SMG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_COMBATPDW_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_COMBATPDW_CLIP_02' },
            { name = "clip_drum", label = ("component_clip_drum"), hash = 'COMPONENT_COMBATPDW_CLIP_03' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_SMALL' },
        },
    },
    {
        name = "WEAPON_GUSENBERG",
        label = ("weapon_gusenberg"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_MG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_GUSENBERG_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_GUSENBERG_CLIP_02' },
        },
    },
    {
        name = "WEAPON_MACHINEPISTOL",
        label = ("weapon_machinepistol"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_MACHINEPISTOL_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_MACHINEPISTOL_CLIP_02' },
            { name = "clip_drum", label = ("component_clip_drum"), hash = 'COMPONENT_MACHINEPISTOL_CLIP_03' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_SUPP' },
        },
    },
    {
        name = "WEAPON_MG",
        label = ("weapon_mg"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_MG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_MG_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_MG_CLIP_02' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_SMALL_02' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_MG_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_MICROSMG",
        label = ("weapon_microsmg"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SMG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_MICROSMG_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_MICROSMG_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_PI_FLSH' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_MACRO' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_MICROSMG_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_MINISMG",
        label = ("weapon_minismg"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SMG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_MINISMG_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_MINISMG_CLIP_02' },
        },
    },
    {
        name = "WEAPON_SMG",
        label = ("weapon_smg"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SMG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_SMG_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_SMG_CLIP_02' },
            { name = "clip_drum", label = ("component_clip_drum"), hash = 'COMPONENT_SMG_CLIP_03' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_MACRO_02' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_SUPP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_SMG_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_TECPISTOL",
        label = ("weapon_tecpistol"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SMG' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_TECPISTOL_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_TECPISTOL_CLIP_02' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_MACRO' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
        },
    },
    {
        name = "WEAPON_SMG_MK2",
        label = ("weapon_smg_mk2"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SMG' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_SMG_MK2_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_SMG_MK2_CLIP_02' },
            { name = "ammo_tracer", label = ("component_ammo_tracer"), hash = 'COMPONENT_SMG_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = ("component_ammo_incendiary"), hash = 'COMPONENT_SMG_MK2_CLIP_INCENDIARY' },
            { name = "ammo_hollowpoint", label = ("component_ammo_hollowpoint"), hash = 'COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT' },
            { name = "ammo_fmj", label = ("component_ammo_fmj"), hash = 'COMPONENT_SMG_MK2_CLIP_FMJ' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope_holo", label = ("component_scope_holo"), hash = 'COMPONENT_AT_SIGHTS_SMG' },
            { name = "scope_small", label = ("component_scope_small"), hash = 'COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2' },
            { name = "scope_medium", label = ("component_scope_medium"), hash = 'COMPONENT_AT_SCOPE_SMALL_SMG_MK2' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_PI_SUPP' },
            { name = "muzzle_flat", label = ("component_muzzle_flat"), hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = ("component_muzzle_tactical"), hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = ("component_muzzle_fat"), hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = ("component_muzzle_precision"), hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = ("component_muzzle_heavy"), hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = ("component_muzzle_slanted"), hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = ("component_muzzle_split"), hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "barrel_default", label = ("component_barrel_default"), hash = 'COMPONENT_AT_SB_BARREL_01' },
            { name = "barrel_heavy", label = ("component_barrel_heavy"), hash = 'COMPONENT_AT_SB_BARREL_02' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_SMG_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_SMG_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_SMG_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_SMG_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_SMG_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_SMG_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_SMG_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_SMG_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_SMG_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_SMG_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_SMG_MK2_CAMO_IND_01' },
        },
    },
    { name = "WEAPON_RAYCARBINE", label = ("weapon_raycarbine"), ammo = { label = ("ammo_rounds"), hash = 'AMMO_SMG' }, tints = Config.DefaultWeaponTints, components = {} },
    -- Rifles
    {
        name = "WEAPON_ADVANCEDRIFLE",
        label = ("weapon_advancedrifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_ADVANCEDRIFLE_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_ADVANCEDRIFLE_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_SMALL' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_ASSAULTRIFLE",
        label = ("weapon_assaultrifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_ASSAULTRIFLE_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_ASSAULTRIFLE_CLIP_02' },
            { name = "clip_drum", label = ("component_clip_drum"), hash = 'COMPONENT_ASSAULTRIFLE_CLIP_03' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_MACRO' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_ASSAULTRIFLE_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_ASSAULTRIFLE_MK2",
        label = ("weapon_assaultrifle_mk2"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_02' },
            { name = "ammo_tracer", label = ("component_ammo_tracer"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = ("component_ammo_incendiary"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = ("component_ammo_armor"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = ("component_ammo_fmj"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope_holo", label = ("component_scope_holo"), hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_small", label = ("component_scope_small"), hash = 'COMPONENT_AT_SCOPE_MACRO_MK2' },
            { name = "scope_large", label = ("component_scope_large"), hash = 'COMPONENT_AT_SCOPE_MEDIUM_MK2' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "muzzle_flat", label = ("component_muzzle_flat"), hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = ("component_muzzle_tactical"), hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = ("component_muzzle_fat"), hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = ("component_muzzle_precision"), hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = ("component_muzzle_heavy"), hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = ("component_muzzle_slanted"), hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = ("component_muzzle_split"), hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "barrel_default", label = ("component_barrel_default"), hash = 'COMPONENT_AT_AR_BARREL_01' },
            { name = "barrel_heavy", label = ("component_barrel_heavy"), hash = 'COMPONENT_AT_AR_BARREL_02' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_BULLPUPRIFLE",
        label = ("weapon_bullpuprifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_BULLPUPRIFLE_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_BULLPUPRIFLE_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_SMALL' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_BULLPUPRIFLE_VARMOD_LOW' },
        },
    },
    {
        name = "WEAPON_BULLPUPRIFLE_MK2",
        label = ("weapon_bullpuprifle_mk2"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_02' },
            { name = "ammo_tracer", label = ("component_ammo_tracer"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = ("component_ammo_incendiary"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = ("component_ammo_armor"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = ("component_ammo_fmj"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope_holo", label = ("component_scope_holo"), hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_small", label = ("component_scope_small"), hash = 'COMPONENT_AT_SCOPE_MACRO_02_MK2' },
            { name = "scope_medium", label = ("component_scope_medium"), hash = 'COMPONENT_AT_SCOPE_SMALL_MK2' },
            { name = "barrel_default", label = ("component_barrel_default"), hash = 'COMPONENT_AT_BP_BARREL_01' },
            { name = "barrel_heavy", label = ("component_barrel_heavy"), hash = 'COMPONENT_AT_BP_BARREL_02' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "muzzle_flat", label = ("component_muzzle_flat"), hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = ("component_muzzle_tactical"), hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = ("component_muzzle_fat"), hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = ("component_muzzle_precision"), hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = ("component_muzzle_heavy"), hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = ("component_muzzle_slanted"), hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = ("component_muzzle_split"), hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_CARBINERIFLE",
        label = ("weapon_carbinerifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_CARBINERIFLE_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_CARBINERIFLE_CLIP_02' },
            { name = "clip_box", label = ("component_clip_box"), hash = 'COMPONENT_CARBINERIFLE_CLIP_03' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_MEDIUM' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_CARBINERIFLE_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_CARBINERIFLE_MK2",
        label = ("weapon_carbinerifle_mk2"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_02' },
            { name = "ammo_tracer", label = ("component_ammo_tracer"), hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = ("component_ammo_incendiary"), hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = ("component_ammo_armor"), hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = ("component_ammo_fmj"), hash = 'COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope_holo", label = ("component_scope_holo"), hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_medium", label = ("component_scope_medium"), hash = 'COMPONENT_AT_SCOPE_MACRO_MK2' },
            { name = "scope_large", label = ("component_scope_large"), hash = 'COMPONENT_AT_SCOPE_MEDIUM_MK2' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "muzzle_flat", label = ("component_muzzle_flat"), hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = ("component_muzzle_tactical"), hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = ("component_muzzle_fat"), hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = ("component_muzzle_precision"), hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = ("component_muzzle_heavy"), hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = ("component_muzzle_slanted"), hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = ("component_muzzle_split"), hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "barrel_default", label = ("component_barrel_default"), hash = 'COMPONENT_AT_CR_BARREL_01' },
            { name = "barrel_heavy", label = ("component_barrel_heavy"), hash = 'COMPONENT_AT_CR_BARREL_02' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_COMPACTRIFLE",
        label = ("weapon_compactrifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_COMPACTRIFLE_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_COMPACTRIFLE_CLIP_02' },
            { name = "clip_drum", label = ("component_clip_drum"), hash = 'COMPONENT_COMPACTRIFLE_CLIP_03' },
        },
    },
    {
        name = "WEAPON_MILITARYRIFLE",
        label = ("weapon_militaryrifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_MILITARYRIFLE_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_MILITARYRIFLE_CLIP_02' },
            { name = "ironsights", label = ("component_ironsights"), hash = 'COMPONENT_MILITARYRIFLE_SIGHT_01' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_SMALL' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
        },
    },
    {
        name = "WEAPON_SPECIALCARBINE",
        label = ("weapon_specialcarbine"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_SPECIALCARBINE_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_SPECIALCARBINE_CLIP_02' },
            { name = "clip_drum", label = ("component_clip_drum"), hash = 'COMPONENT_SPECIALCARBINE_CLIP_03' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_MEDIUM' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER' },
        },
    },
    {
        name = "WEAPON_SPECIALCARBINE_MK2",
        label = ("weapon_specialcarbine_mk2"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_02' },
            { name = "ammo_tracer", label = ("component_ammo_tracer"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = ("component_ammo_incendiary"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = ("component_ammo_armor"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = ("component_ammo_fmj"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope_holo", label = ("component_scope_holo"), hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_small", label = ("component_scope_small"), hash = 'COMPONENT_AT_SCOPE_MACRO_MK2' },
            { name = "scope_large", label = ("component_scope_large"), hash = 'COMPONENT_AT_SCOPE_MEDIUM_MK2' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "muzzle_flat", label = ("component_muzzle_flat"), hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = ("component_muzzle_tactical"), hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = ("component_muzzle_fat"), hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = ("component_muzzle_precision"), hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = ("component_muzzle_heavy"), hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = ("component_muzzle_slanted"), hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = ("component_muzzle_split"), hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "barrel_default", label = ("component_barrel_default"), hash = 'COMPONENT_AT_SC_BARREL_01' },
            { name = "barrel_heavy", label = ("component_barrel_heavy"), hash = 'COMPONENT_AT_SC_BARREL_02' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_HEAVYRIFLE",
        label = ("weapon_heavyrifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_HEAVYRIFLE_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_HEAVYRIFLE_CLIP_02' },
            { name = "scope_holo", label = ("component_scope_holo"), hash = 'COMPONENT_HEAVYRIFLE_SIGHT_01' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_MEDIUM' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
        },
    },
    -- Sniper
    {
        name = "WEAPON_HEAVYSNIPER",
        label = ("weapon_heavysniper"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SNIPER' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_LARGE' },
            { name = "scope_advanced", label = ("component_scope_advanced"), hash = 'COMPONENT_AT_SCOPE_MAX' },
        },
    },
    {
        name = "WEAPON_HEAVYSNIPER_MK2",
        label = ("weapon_heavysniper_mk2"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SNIPER' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_02' },
            { name = "ammo_incendiary", label = ("component_ammo_incendiary"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = ("component_ammo_armor"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = ("component_ammo_fmj"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ' },
            { name = "ammo_explosive", label = ("component_ammo_explosive"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE' },
            { name = "scope_zoom", label = ("component_scope_zoom"), hash = 'COMPONENT_AT_SCOPE_LARGE_MK2' },
            { name = "scope_advanced", label = ("component_scope_advanced"), hash = 'COMPONENT_AT_SCOPE_MAX' },
            { name = "scope_nightvision", label = ("component_scope_nightvision"), hash = 'COMPONENT_AT_SCOPE_NV' },
            { name = "scope_thermal", label = ("component_scope_thermal"), hash = 'COMPONENT_AT_SCOPE_THERMAL' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_SR_SUPP_03' },
            { name = "muzzle_squared", label = ("component_muzzle_squared"), hash = 'COMPONENT_AT_MUZZLE_08' },
            { name = "muzzle_bell", label = ("component_muzzle_bell"), hash = 'COMPONENT_AT_MUZZLE_09' },
            { name = "barrel_default", label = ("component_barrel_default"), hash = 'COMPONENT_AT_SR_BARREL_01' },
            { name = "barrel_heavy", label = ("component_barrel_heavy"), hash = 'COMPONENT_AT_SR_BARREL_02' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_MARKSMANRIFLE",
        label = ("weapon_marksmanrifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SNIPER' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_MARKSMANRIFLE_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_MARKSMANRIFLE_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_MARKSMANRIFLE_VARMOD_LUXE' },
        },
    },
    {
        name = "WEAPON_MARKSMANRIFLE_MK2",
        label = ("weapon_marksmanrifle_mk2"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SNIPER' },
        tints = Config.MK2WeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_02' },
            { name = "ammo_tracer", label = ("component_ammo_tracer"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER' },
            { name = "ammo_incendiary", label = ("component_ammo_incendiary"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY' },
            { name = "ammo_armor", label = ("component_ammo_armor"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING' },
            { name = "ammo_fmj", label = ("component_ammo_fmj"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ' },
            { name = "scope_holo", label = ("component_scope_holo"), hash = 'COMPONENT_AT_SIGHTS' },
            { name = "scope_large", label = ("component_scope_large"), hash = 'COMPONENT_AT_SCOPE_MEDIUM_MK2' },
            { name = "scope_zoom", label = ("component_scope_zoom"), hash = 'COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
            { name = "muzzle_flat", label = ("component_muzzle_flat"), hash = 'COMPONENT_AT_MUZZLE_01' },
            { name = "muzzle_tactical", label = ("component_muzzle_tactical"), hash = 'COMPONENT_AT_MUZZLE_02' },
            { name = "muzzle_fat", label = ("component_muzzle_fat"), hash = 'COMPONENT_AT_MUZZLE_03' },
            { name = "muzzle_precision", label = ("component_muzzle_precision"), hash = 'COMPONENT_AT_MUZZLE_04' },
            { name = "muzzle_heavy", label = ("component_muzzle_heavy"), hash = 'COMPONENT_AT_MUZZLE_05' },
            { name = "muzzle_slanted", label = ("component_muzzle_slanted"), hash = 'COMPONENT_AT_MUZZLE_06' },
            { name = "muzzle_split", label = ("component_muzzle_split"), hash = 'COMPONENT_AT_MUZZLE_07' },
            { name = "barrel_default", label = ("component_barrel_default"), hash = 'COMPONENT_AT_MRFL_BARREL_01' },
            { name = "barrel_heavy", label = ("component_barrel_heavy"), hash = 'COMPONENT_AT_MRFL_BARREL_02' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP_02' },
            { name = "camo_finish", label = ("component_camo_finish"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO' },
            { name = "camo_finish2", label = ("component_camo_finish2"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_02' },
            { name = "camo_finish3", label = ("component_camo_finish3"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_03' },
            { name = "camo_finish4", label = ("component_camo_finish4"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_04' },
            { name = "camo_finish5", label = ("component_camo_finish5"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_05' },
            { name = "camo_finish6", label = ("component_camo_finish6"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_06' },
            { name = "camo_finish7", label = ("component_camo_finish7"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_07' },
            { name = "camo_finish8", label = ("component_camo_finish8"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_08' },
            { name = "camo_finish9", label = ("component_camo_finish9"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_09' },
            { name = "camo_finish10", label = ("component_camo_finish10"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_10' },
            { name = "camo_finish11", label = ("component_camo_finish11"), hash = 'COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01' },
        },
    },
    {
        name = "WEAPON_SNIPERRIFLE",
        label = ("weapon_sniperrifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SNIPER' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "scope", label = ("component_scope"), hash = 'COMPONENT_AT_SCOPE_LARGE' },
            { name = "scope_advanced", label = ("component_scope_advanced"), hash = 'COMPONENT_AT_SCOPE_MAX' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
            { name = "luxary_finish", label = ("component_luxary_finish"), hash = 'COMPONENT_SNIPERRIFLE_VARMOD_LUXE' },
        },
    },
    -- Heavy / Launchers
    {
        name = "WEAPON_COMPACTLAUNCHER",
        label = ("weapon_compactlauncher"),
        tints = Config.DefaultWeaponTints,
        components = {},
        ammo = { label = ("ammo_grenadelauncher"), hash = 'AMMO_GRENADELAUNCHER' },
    },
    { name = "WEAPON_FIREWORK", label = ("weapon_firework"), components = {}, ammo = { label = ("ammo_firework"), hash = 'AMMO_FIREWORK' } },
    {
        name = "WEAPON_GRENADELAUNCHER",
        label = ("weapon_grenadelauncher"),
        tints = Config.DefaultWeaponTints,
        components = {},
        ammo = { label = ("ammo_grenadelauncher"), hash = 'AMMO_GRENADELAUNCHER' },
    },
    { name = "WEAPON_HOMINGLAUNCHER", label = ("weapon_hominglauncher"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_rockets"), hash = 'AMMO_HOMINGLAUNCHER' } },
    { name = "WEAPON_MINIGUN", label = ("weapon_minigun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_rounds"), hash = 'AMMO_MINIGUN' } },
    { name = "WEAPON_RAILGUN", label = ("weapon_railgun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_rounds"), hash = 'AMMO_RAILGUN' } },
    { name = "WEAPON_RPG", label = ("weapon_rpg"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_rockets"), hash = 'AMMO_RPG' } },
    { name = "WEAPON_RAYMINIGUN", label = ("weapon_rayminigun"), tints = Config.DefaultWeaponTints, components = {}, ammo = { label = ("ammo_rounds"), hash = 'AMMO_MINIGUN' } },
    -- Thrown
    { name = "WEAPON_BALL", label = ("weapon_ball"), components = {}, ammo = { label = ("ammo_ball"), hash = 'AMMO_BALL' }, throwable = true },
    { name = "WEAPON_BZGAS", label = ("weapon_bzgas"), components = {}, ammo = { label = ("ammo_bzgas"), hash = 'AMMO_BZGAS' }, throwable = true },
    { name = "WEAPON_FLARE", label = ("weapon_flare"), components = {}, ammo = { label = ("ammo_flare"), hash = 'AMMO_FLARE' }, throwable = true },
    { name = "WEAPON_GRENADE", label = ("weapon_grenade"), components = {}, ammo = { label = ("ammo_grenade"), hash = 'AMMO_GRENADE' }, throwable = true },
    { name = "WEAPON_PETROLCAN", label = ("weapon_petrolcan"), components = {}, ammo = { label = ("ammo_petrol"), hash = 'AMMO_PETROLCAN' }, throwable = true },
    { name = "WEAPON_HAZARDCAN", label = ("weapon_hazardcan"), components = {}, ammo = { label = ("ammo_petrol"), hash = 'AMMO_PETROLCAN' }, throwable = true },
    { name = "WEAPON_MOLOTOV", label = ("weapon_molotov"), components = {}, ammo = { label = ("ammo_molotov"), hash = 'AMMO_MOLOTOV' }, throwable = true },
    { name = "WEAPON_PROXMINE", label = ("weapon_proxmine"), components = {}, ammo = { label = ("ammo_proxmine"), hash = 'AMMO_PROXMINE' }, throwable = true },
    { name = "WEAPON_PIPEBOMB", label = ("weapon_pipebomb"), components = {}, ammo = { label = ("ammo_pipebomb"), hash = 'AMMO_PIPEBOMB' }, throwable = true },
    { name = "WEAPON_SNOWBALL", label = ("weapon_snowball"), components = {}, ammo = { label = ("ammo_snowball"), hash = 'AMMO_SNOWBALL' }, throwable = true },
    { name = "WEAPON_STICKYBOMB", label = ("weapon_stickybomb"), components = {}, ammo = { label = ("ammo_stickybomb"), hash = 'AMMO_STICKYBOMB' }, throwable = true },
    { name = "WEAPON_SMOKEGRENADE", label = ("weapon_smokegrenade"), components = {}, ammo = { label = ("ammo_smokebomb"), hash = 'AMMO_SMOKEGRENADE' }, throwable = true },
    -- Tools
    { name = "WEAPON_FIREEXTINGUISHER", label = ("weapon_fireextinguisher"), components = {}, ammo = { label = ("ammo_charge"), hash = 'AMMO_FIREEXTINGUISHER' } },
    { name = "WEAPON_DIGISCANNER", label = ("weapon_digiscanner"), components = {} },
    { name = "GADGET_PARACHUTE", label = ("gadget_parachute"), components = {}, throwable = true },
    {
        name = "WEAPON_TACTICALRIFLE",
        label = ("weapon_tactilerifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_TACTICALRIFLE_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_TACTICALRIFLE_CLIP_02' },
            { name = "flashlight", label = ("component_flashlight"), hash = 'COMPONENT_AT_AR_FLSH_REH' },
            { name = "grip", label = ("component_grip"), hash = 'COMPONENT_AT_AR_AFGRIP' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP_02' },
        },
    },
    {
        name = "WEAPON_BATTLERIFLE",
        label = ("weapon_battlerifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_BATTLERIFLE_CLIP_01' },
            { name = "clip_extended", label = ("component_clip_extended"), hash = 'COMPONENT_BATTLERIFLE_CLIP_02' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_AT_AR_SUPP' },
        },
    },
    {
        name = "WEAPON_SNOWLAUNCHER",
        label = ("weapon_snowlauncher"),
        ammo = { label = ("ammo_snowball"), hash = 'AMMO_SNOWLAUNCHER' },
        tints = Config.DefaultWeaponTints,
        components = {},
    },
    {
        name = "WEAPON_HACKINGDEVICE",
        label = ("weapon_hackingdevice"),
        tints = Config.DefaultWeaponTints,
        components = {},
    },
    {
        name = "WEAPON_PRECISIONRIFLE",
        label = ("weapon_precisionrifle"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_SNIPER' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_PRECISIONRIFLE_CLIP_01' },
        },
    },
    { name = "WEAPON_METALDETECTOR", label = ("weapon_metaldetector"), components = {} },
    {
        name = "WEAPON_PISTOLXM3",
        label = ("weapon_pistolxm3"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_PISTOLXM3_CLIP_01' },
            { name = "suppressor", label = ("component_suppressor"), hash = 'COMPONENT_PISTOLXM3_SUPP' },
        },
    },
    { name = "WEAPON_ACIDPACKAGE", label = ("weapon_acidpackage"), components = {}, throwable = true },
    { name = "WEAPON_CANDYCANE", label = ("weapon_candycane"), components = {} },
    {
        name = "WEAPON_RAILGUNXM3",
        label = ("weapon_railgunxm3"),
        ammo = { label = ("ammo_rounds"), hash = 'AMMO_RAILGUN' },
        tints = Config.DefaultWeaponTints,
        components = {
            { name = "clip_default", label = ("component_clip_default"), hash = 'COMPONENT_RAILGUNXM3_CLIP_01' },
        },
    },
    { name = "weapon_glock19gen4", label = ("weapon_glock19gen4"), components = {}, throwable = true },
    { name = "WEAPON_LWRC", label = ("WEAPON_LWRC"), ammo = { label = ("ammo_rounds"), hash = 'AMMO_RIFLE' }, components = {}, throwable = true },
    { name = "WEAPON_G19", label = ("WEAPON_G19"), ammo = { label = ("ammo_rounds"), hash = 'AMMO_PISTOL' }, components = {}, throwable = true },

}
