---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by laure.
--- DateTime: 24/03/2025 17:36
---

local playersAnim = {}


RegisterNetEvent("vfw:anim:sharedContext", function(targetId)
    local src = source
    local target = VFW.GetPlayerFromId(targetId)
    if not target then
        return
    end

    local xPlayer = VFW.GetPlayerFromId(src)
    if not playersAnim[src] then
        return
    end

    TriggerClientEvent("vfw:anim:askShared", targetId, src, xPlayer.name, playersAnim[src].anim)
end)


RegisterNetEvent("removeLastAnim", function()
    local src = source
    local xPlayer = VFW.GetPlayerFromId(src)
    if not xPlayer then
        return
    end
    if not playersAnim[src] then
        return
    end
    playersAnim[src] = nil
end)

RegisterNetEvent("vfw:anim:requestShared", function(targetId, nameEmote)
    local src = source
    local target = VFW.GetPlayerFromId(targetId)
    if not target then
        return
    end
    local xPlayer = VFW.GetPlayerFromId(src)
    TriggerClientEvent("vfw:anim:askShared", targetId, src, xPlayer.name,nameEmote)
end)

RegisterNetEvent("vfw:anim:acceptShared", function(ask, emote)
    local src = source
    local target = VFW.GetPlayerFromId(ask)
    if not target then
        return
    end
    TriggerClientEvent("SyncPlayEmote", src, emote, ask)
    TriggerClientEvent("SyncPlayEmoteSource", ask, emote, src)

end)

RegisterNetEvent("vfw:anim:refuseShared", function(targetId, emote)
    local target = VFW.GetPlayerFromId(targetId)
    if not target then
        return
    end
    target.showNotification({
        type = 'ROUGE',
        content = "Le joueur a refusé votre demande d'animation"
    })
end)

RegisterServerCallback("vfw:anim:copy", function(source, targetId)
    local target = VFW.GetPlayerFromId(targetId)
    if not target then
        return
    end

    if not playersAnim[targetId] then
        return
    end

    return playersAnim[targetId].anim
end)

AddEventHandler('playerDropped', function()
    local Source = source
    if playersAnim[Source] then
        playersAnim[Source] = nil
    end
end)

RegisterNetEvent("vfw:anim:sync", function(animName)
    local src = source
    local xPlayer = VFW.GetPlayerFromId(src)
    if not xPlayer then
        return
    end
    if not playersAnim[src] then
        playersAnim[src] = {}
    end
    console.debug("Anim saved", animName, "for", src)
    playersAnim[src].anim = animName
end)