---
--- Generated by CfxEmmyLua(https://gitlab.madelew.com/wmade/cfx-EmmyLua/)
--- Created by laure.
--- DateTime: 09/05/2025 23:15
--- Version: 1.0.0
---

function string:split(sep)
    local result = {}
    local pattern = string.format("([^%s]+)", sep)
    for match in self:gmatch(pattern) do
        table.insert(result, match)
    end
    return result
end


local datas = {}


local getData = function(xPlayer, type)
    local nameSplit = xPlayer.name:split(" ")
    local lname = nameSplit[1]
    local fname = nameSplit[2]



    if not datas[xPlayer.getIdentifier()] then
        local data = MySQL.Sync.fetchAll("SELECT sex, height, skin, dateofbirth FROM users WHERE identifier = @identifier ", {
            ["identifier"] = xPlayer.getIdentifier()
        })
        datas[xPlayer.getIdentifier()] = data[1]
    end

    local property = VFW.GetProperty("player:"..xPlayer.id)

    local data = datas[xPlayer.getIdentifier()]
    return {
        type = type and type or "identity",
        lastName = lname,
        dl= ("License: %s"):format(xPlayer.id),
        firstName = fname,
        date_of_birth = data["dateofbirth"],
        height = data["height"] or 180,
        sex = data["sex"],
        photo = xPlayer.mugshot,
        address = property and property.name or "Aucune adresse"
    }
end

RegisterNetEvent("core:identity:display", function(target, type)
    local xPlayer = VFW.GetPlayerFromId(target)
    if not xPlayer then return end
    xPlayer.triggerEvent("core:identity:show", getData(xPlayer, type))
end)

RegisterServerCallback("identity:getData", function(src, ...)
    local xPlayer = VFW.GetPlayerFromId(src)

    return getData(xPlayer)

end)

RegisterNetEvent("identity:givemycard", function()
    local src = source
    local xPlayer = VFW.GetPlayerFromId(src)

    print("item ",  xPlayer.hasItem("identitycard", 1) )
    if xPlayer.hasItem("identitycard", 1) then
        xPlayer.showNotification({
            type = 'ROUGE',
            content = "Vous avez déja recu votre carte",
        })
        return
    end

    xPlayer.showNotification({
        type = "VERT",
        content= "Vous venez de recevoir votre pièce d'identité"
    })
    xPlayer.createItem("identitycard", 1)
    xPlayer.updateInventory()
end)

VFW.RegisterUsableItem("identitycard", function(xPlayer, deleteCallback, metaData)
    TriggerClientEvent("identity:opencard", xPlayer.source, "identity")
end)

VFW.RegisterUsableItem("driverlicense", function(xPlayer, deleteCallback, metaData)
    TriggerClientEvent("identity:opencard", xPlayer.source, "driver")
end)

RegisterNetEvent("playerDropped", function(source)
    local xPlayer = VFW.GetPlayerFromId(source)
    -- TODO remove on datas table
end)