VFW.Boatdealer = {}

VFW.Boatdealer.Vehicle = {
    ["Avions"] = {
        { label = "Luxor Deluxe", model = "luxor2",   price = 700000},
        { label = "Alpha-Z1",    model = "alphaz1",  price = 437500},
        { label = "Besra",       model = "besra",    price = 626500},
        { label = "Cuban 800",    model = "cuban800", price = 416500},
        { label = "Howard NX-25", model = "howard",   price = 472500},
        { label = "Luxor",        model = "luxor",    price = 630000},
        { label = "Mammatus",     model = "mammatus", price = 350000},
        { label = "Nimbus",       model = "nimbus",   price = 560000},
        { label = "Nokota",       model = "nokota",   price = 427000},
        { label = "Rogue",        model = "rogue",    price = 497000},
        { label = "Velum",        model = "velum",    price = 402500},
        { label = "Vestra",       model = "vestra",   price = 437500},
        { label = "Dodo",         model = "dodo",     price = 385000},
        { label = "Seabreeze",    model = "seabreeze", price = 346500},
        { label = "Microlight",   model = "microlight", price = 35000},
    },
    ["Hélicopters"] = {
        { label = "Buzzard",      model = "buzzard2",     price = 440000},
        { label = "Cargobob",     model = "cargobob2",    price = 600000},
        { label = "Frogger",      model = "frogger",      price = 360000},
        { label = "Havok",        model = "havok",        price = 280000},
        { label = "Maverick",     model = "maverick",     price = 400000},
        { label = "Seasparrow",   model = "seasparrow",   price = 520000},
        { label = "SuperVolito",  model = "supervolito",  price = 540000},
        { label = "SuperVolito Carbon", model = "supervolito2", price = 560000},
        { label = "Swift",        model = "swift",        price = 572000},
        { label = "Swift Deluxe", model = "swift2",       price = 800000},
        { label = "Volatus",      model = "volatus",      price = 760000},
    },
    ["Bateaux"] = {
        { label = "Dinghy",       model = "dinghy",   price = 48750},
        { label = "Tug",          model = "tug",      price = 32500},
        { label = "Dinghy 2",     model = "dinghy2",  price = 29250},
        { label = "Jetmax",       model = "jetmax",   price = 61750},
        { label = "Longfin",      model = "longfin",  price = 97500},
        { label = "Marquis",      model = "marquis",  price = 185250},
        { label = "Seashark",     model = "seashark", price = 16250},
        { label = "Speeder",      model = "speeder",  price = 81250},
        { label = "Squalo",       model = "squalo",   price = 68250},
        { label = "Suntrap",      model = "suntrap",  price = 35750},
        { label = "Toro",         model = "toro",     price = 117000},
        { label = "Toro Yacht",   model = "toro2",    price = 126750},
        { label = "Tropic",        model = "tropic",   price = 26000},
        { label = "Avisa",         model = "avisa",    price = 113750},
    }
}