RegisterNetEvent("vfw:playerReady", function()
    Wait(5000)
    Society.loadStockage(VFW.PlayerData.job.name)
    Society.loadCasier(VFW.PlayerData.job.name)
    Society.loadVetement(VFW.PlayerData.job.name)
    Society.loadFarm(VFW.PlayerData.job.name)
    Society.loadGarage(VFW.PlayerData.job.name)
    Society.loadCraft(VFW.PlayerData.job.name)
    Society.loadGestion(VFW.PlayerData.job.name)
    Society.loadCatalogue()
    Society.loadSonnette()
    Society.loadBlips()
end)

RegisterNetEvent("vfw:setJob", function(Job)
    Wait(5000)
    Society.loadStockage(Job.name)
    Society.loadCasier(Job.name)
    Society.loadVetement(Job.name)
    Society.loadFarm(Job.name)
    Society.loadGarage(Job.name)
    Society.loadCraft(Job.name)
    Society.loadGestion(Job.name)
end)