---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by laure.
--- DateTime: 07/04/2025 17:58
---


---@class Heist
------@field id number
------@field heist_type string
--------@field heist_label string
---------@field ped_model string
---------@field ped_position vector3
---------@field cops_required number
---------@field crew_level_required number
---------@field max_reward number
---------@field heist_location boolean
---------@field xp_reward number
function CreateHeists(id, heist_type, heist_label, ped_model, ped_position, cops_required, crew_level_required, max_reward, heist_location, xp_reward)

    local self = {}

    self.id = id
    self.heist_type = heist_type
    self.heist_label = heist_label
    self.ped_model = ped_model
    self.ped_position = ped_position
    self.cops_required = cops_required
    self.crew_level_required = crew_level_required
    self.max_reward = max_reward
    self.heist_location = heist_location
    self.xp_reward = xp_reward



    return self


end